name: "Provision AWS Resources using Terraform"

on:
  workflow_dispatch:
    inputs:
      resource:
        type: choice
        description: Choose the resource
        options:
        - ./staging/eks
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
        - terraform_apply
        - terraform_destroy

jobs:
  terraform:
    name: "Provision VPC and EKS Cluster"
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init -migrate-state
        working-directory: ${{ github.event.inputs.resource }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ github.event.inputs.resource }}

      - name: Terraform Format
        run: terraform fmt
        working-directory: ${{ github.event.inputs.resource }}

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'terraform_apply' }}
        run: terraform apply -auto-approve
        working-directory: ${{ github.event.inputs.resource }}

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'terraform_destroy' }}
        run: terraform destroy -auto-approve
        working-directory: ${{ github.event.inputs.resource }}

